#!/usr/bin/env python3
"""Helpers for the three-service local stack (capabilities-ai, core-engine, rx-analytics)."""

from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import sys
import time
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_HOME = SCRIPT_DIR.parent
STACK_CONFIG = Path(os.environ.get("LOCAL_STACK_CONFIG", REPO_HOME / "config" / "local-stack.json"))
STACK_SECRETS = Path(os.environ.get("LOCAL_STACK_SECRETS", REPO_HOME / ".env.stack"))
STACK_EXAMPLE = REPO_HOME / ".env.stack.example"
LOCAL_ENV_DIR = REPO_HOME / "config" / "local-env"
CHECKOUT_ROOT = Path(
    os.environ.get("DEV_REPOS_CHECKOUT_ROOT", os.environ.get("DEV_REPOS_ROOT", REPO_HOME) + "/repos")
)
if "DEV_REPOS_ROOT" in os.environ and "DEV_REPOS_CHECKOUT_ROOT" not in os.environ:
    CHECKOUT_ROOT = Path(os.environ["DEV_REPOS_ROOT"]) / "repos"

TMUX_SESSION = os.environ.get("LOCAL_STACK_TMUX_SESSION", "local-stack")


def load_stack() -> dict:
    """Loads the local stack manifest."""
    with STACK_CONFIG.open() as handle:
        return json.load(handle)


def parse_env_file(path: Path) -> dict[str, str]:
    """Parses KEY=value lines from an env file, ignoring comments and blanks."""
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for line in path.read_text().splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if "=" not in stripped:
            continue
        key, _, raw = stripped.partition("=")
        values[key.strip()] = raw.strip().strip('"').strip("'")
    return values


def format_env_value(value: str) -> str:
    """Quotes values that need quoting in dotenv files."""
    if re.search(r'[\s#"\'\\]', value):
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    return value


def write_env_file(path: Path, values: dict[str, str]) -> None:
    """Writes a sorted dotenv file from a key/value map."""
    lines = [
        "# Generated by local-dev env — edit .env.stack or config/local-env/* instead.",
        "",
    ]
    for key in sorted(values):
        lines.append(f"{key}={format_env_value(values[key])}")
    lines.append("")
    path.write_text("\n".join(lines))


def merge_env(*layers: dict[str, str]) -> dict[str, str]:
    """Later layers override earlier keys."""
    merged: dict[str, str] = {}
    for layer in layers:
        merged.update(layer)
    return {k: v for k, v in merged.items() if v != ""}


def repo_dir(repo_slug: str) -> Path:
    """Returns the checkout path for org/repo."""
    return CHECKOUT_ROOT / repo_slug


def service_paths(service_key: str, service: dict) -> tuple[Path, list[Path]]:
    """Returns repo root and env file paths for a service."""
    root = repo_dir(service["repo"])
    env_paths = [root / name for name in service["env_files"]]
    return root, env_paths


def map_stack_secrets(secrets: dict[str, str], service_key: str) -> dict[str, str]:
    """Maps shared .env.stack keys onto per-service variable names."""
    mapped = dict(secrets)
    cap_db = secrets.get("DB_CONNECTION_STRING", "")
    core_db = secrets.get("DB_CONNECTION_STRING_CORE_ENGINE", "")
    doc_db = secrets.get("DB_CONNECTION_STRING_DOC_MANAGER", "")

    if service_key == "capabilities-ai":
        if cap_db:
            mapped["DB_CONNECTION_STRING"] = cap_db
        if doc_db:
            mapped["DB_CONNECTION_STRING_DOC_MANAGER"] = doc_db
        if core_db:
            mapped["DB_CONNECTION_STRING_CORE_ENGINE"] = core_db
    elif service_key == "core-engine":
        if core_db:
            mapped["DB_CONNECTION_STRING"] = core_db
        if doc_db:
            mapped["DB_CONNECTION_STRING_DOC_MANAGER"] = doc_db
        if cap_db:
            mapped["DB_CONNECTION_STRING_CAPABILITIES_AI"] = cap_db
    return mapped


def sync_env_files() -> None:
    """Builds per-repo env files wired for localhost cross-service URLs."""
    if not STACK_SECRETS.exists():
        print(f"Missing secrets file: {STACK_SECRETS}", file=sys.stderr)
        print(f"Copy {STACK_EXAMPLE} to {STACK_SECRETS} and fill in values.", file=sys.stderr)
        raise SystemExit(2)

    stack = load_stack()
    secrets = parse_env_file(STACK_SECRETS)
    cross_links: dict[str, dict[str, str]] = stack.get("cross_links", {})
    shared = stack.get("shared", {})

    for service_key, service in stack["services"].items():
        root, env_paths = service_paths(service_key, service)
        if not root.is_dir():
            print(f"skip missing repo: {root}", file=sys.stderr)
            continue

        overlay_name = {
            "capabilities-ai": "capabilities-ai.env",
            "core-engine": "core-engine.env",
            "rx-analytics": "rx-analytics.env.local",
        }[service_key]
        overlay = parse_env_file(LOCAL_ENV_DIR / overlay_name)
        example_path = root / (
            ".env.example" if service_key != "rx-analytics" else ".env.example"
        )
        example = parse_env_file(example_path)
        merged = merge_env(
            example,
            shared,
            map_stack_secrets(secrets, service_key),
            cross_links.get(service_key, {}),
            overlay,
        )
        for env_path in env_paths:
            write_env_file(env_path, merged)
            print(f"wrote {env_path}")


def run_git_clone(command: list[str], cwd: Path | None = None) -> None:
    """Runs git with Cursor's HTTPS rewrite disabled so SSH org access works."""
    env = os.environ.copy()
    env["GIT_CONFIG_GLOBAL"] = "/dev/null"
    env["GIT_CONFIG_SYSTEM"] = "/dev/null"
    subprocess.run(command, cwd=cwd, check=True, env=env)


def ensure_repos(selectors: list[str] | None = None) -> None:
    """Clones configured stack repos when missing."""
    stack = load_stack()
    wanted = set(selectors or stack["services"])
    for service_key, service in stack["services"].items():
        if selectors and service_key not in wanted:
            continue
        root = repo_dir(service["repo"])
        if (root / ".git").is_dir():
            print(f"exists: {root}")
            continue
        root.parent.mkdir(parents=True, exist_ok=True)
        url = f"git@github.com:{service['repo']}.git"
        print(f"cloning {url} -> {root}")
        run_git_clone(["git", "clone", url, str(root)])


def install_deps(selectors: list[str] | None = None) -> None:
    """Runs bun install in each service package root."""
    stack = load_stack()
    for service_key, service in stack["services"].items():
        if selectors and service_key not in selectors:
            continue
        root = repo_dir(service["repo"])
        pkg = root / service.get("package_root", "") / "package.json"
        if not pkg.exists():
            pkg = root / "package.json"
        if not pkg.exists():
            print(f"skip no package.json: {root}")
            continue
        print(f"install: {root}")
        subprocess.run(["bun", "install"], cwd=root, check=True)


def infra_up() -> None:
    """Starts local Redis via docker compose."""
    compose_file = REPO_HOME / "docker-compose.local.yml"
    subprocess.run(
        ["docker", "compose", "-f", str(compose_file), "up", "-d"],
        cwd=REPO_HOME,
        check=True,
    )


def infra_down() -> None:
    """Stops local Redis."""
    compose_file = REPO_HOME / "docker-compose.local.yml"
    subprocess.run(
        ["docker", "compose", "-f", str(compose_file), "down"],
        cwd=REPO_HOME,
        check=False,
    )


def wait_for_url(url: str, timeout_s: int = 90) -> bool:
    """Polls an HTTP URL until it responds or timeout."""
    deadline = time.time() + timeout_s
    while time.time() < deadline:
        try:
            subprocess.run(
                ["curl", "-sf", "-o", "/dev/null", url],
                check=True,
                capture_output=True,
            )
            return True
        except subprocess.CalledProcessError:
            time.sleep(2)
    return False


def tmux_has_session() -> bool:
    """Returns True when the local-stack tmux session exists."""
    result = subprocess.run(
        ["tmux", "has-session", "-t", TMUX_SESSION],
        capture_output=True,
    )
    return result.returncode == 0


def start_servers(selectors: list[str] | None = None) -> None:
    """Starts dev servers in a tmux session (core-engine, capabilities, rx-analytics)."""
    stack = load_stack()
    order = ["core-engine", "capabilities-ai", "rx-analytics"]
    services = [k for k in order if k in stack["services"]]
    if selectors:
        services = [k for k in services if k in selectors]

    if shutil.which("tmux") is None:
        print("tmux is required for local-dev start", file=sys.stderr)
        raise SystemExit(1)

    if tmux_has_session():
        subprocess.run(["tmux", "kill-session", "-t", TMUX_SESSION], check=False)

    first = True
    for service_key in services:
        service = stack["services"][service_key]
        root = repo_dir(service["repo"])
        if not root.is_dir():
            print(f"skip missing repo: {root}", file=sys.stderr)
            continue
        cmd = f"cd {root} && {service['dev_command']}"
        if first:
            subprocess.run(
                ["tmux", "new-session", "-d", "-s", TMUX_SESSION, "-c", str(root), cmd],
                check=True,
            )
            first = False
        else:
            subprocess.run(
                ["tmux", "split-window", "-t", TMUX_SESSION, "-c", str(root), cmd],
                check=True,
            )
    if not first:
        subprocess.run(["tmux", "select-layout", "-t", TMUX_SESSION, "tiled"], check=True)
        print(f"tmux session '{TMUX_SESSION}' started. Attach with: tmux attach -t {TMUX_SESSION}")

        for service_key in services:
            service = stack["services"][service_key]
            url = service.get("health_url", f"http://localhost:{service['port']}/")
            print(f"waiting for {service_key} at {url} ...")
            if wait_for_url(url, timeout_s=120):
                print(f"  ok: {service_key}")
            else:
                print(f"  timeout: {service_key} (server may still be starting)", file=sys.stderr)


def print_status() -> None:
    """Prints ports and health URLs for the stack."""
    stack = load_stack()
    print("Local stack (cross-wired):")
    for service_key, service in stack["services"].items():
        root = repo_dir(service["repo"])
        state = "cloned" if root.is_dir() else "missing"
        print(
            f"  {service_key}: port {service['port']} ({state}) -> {service.get('health_url', '')}"
        )
    print("\nCross-links:")
    for service_key, links in stack.get("cross_links", {}).items():
        for key, value in links.items():
            print(f"  {service_key}: {key}={value}")
